
# apiVersion: apps/v1
# n-app/templates/service.yaml

# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "my-python-app.fullname" . }}
#   labels:
#     {{- include "my-python-app.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 80
#   selector:
#     {{- include "my-python-app.selectorLabels" . | nindent 4 }}

# kind: Deployment
# metadata:
#   name: {{ include "my-python-app.fullname" . }}
#   labels:
#     {{- include "my-python-app.labels" . | nindent 4 }}
# spec:
#   {{- if not .Values.autoscaling.enabled }}
#   replicas: {{ .Values.replicaCount }}
#   {{- end }}
#   selector:
#     matchLabels:
#       {{- include "my-python-app.selectorLabels" . | nindent 6 }}
#   template:
#     metadata:
#       {{- with .Values.podAnnotations }}
#       annotations:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       labels:
#         {{- include "my-python-app.labels" . | nindent 8 }}
#         {{- with .Values.podLabels }}
#         {{- toYaml . | nindent 8 }}
#         {{- end }}
#     spec:
#       {{- with .Values.imagePullSecrets }}
#       imagePullSecrets:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#       serviceAccountName: {{ include "my-python-app.serviceAccountName" . }}
#       securityContext:
#         {{- toYaml .Values.podSecurityContext | nindent 8 }}
#       containers:
#         - name: {{ .Chart.Name }}
#           securityContext:
#             {{- toYaml .Values.securityContext | nindent 12 }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: {{ .Values.service.port }}
#               protocol: TCP
#           livenessProbe:
#             {{- toYaml .Values.livenessProbe | nindent 12 }}
#           readinessProbe:
#             {{- toYaml .Values.readinessProbe | nindent 12 }}
#           resources:
#             {{- toYaml .Values.resources | nindent 12 }}
#           {{- with .Values.volumeMounts }}
#           volumeMounts:


# my-python-app/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-python-app.fullname" . }}
  labels:
    {{- include "my-python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "my-python-app.selectorLabels" . | nindent 4 }}
